---
driver:
  name: vagrant
  provider: virtualbox

provisioner:
  name: chef_zero
  # Allows install of chef client from internet
  http_proxy: <%= ENV['http_proxy'] %>
  https_proxy: <%= ENV['https_proxy'] %>
  no_proxy: <%= ENV['no_proxy'] %>
  require_chef_omnibus: <%= ENV['CHEF_VERSION'] || '12.11.18' %>
  chef_omnibus_url: https://omnitruck.chef.io/install.sh
  # require_chef_omnibus: false

platforms:
  - name: leap
    driver:
      gui: false
      box: opensuse.leap.42.1
      box_url: <%= ENV['VAGRANT_BOX_REPOSITORY'] %>/opensuse.leap.json
      box_check_update: true
      # By default hostname is randomly generated
      # vm_hostname: leap.example.com
      communicator: ssh
      guest: suse
      customize:
        cpus: 1
        memory: 2048
        natdnshostresolver1: 'on'
        natdnsproxy1: 'on'
        usb: 'off'
      network:
        - ['forwarded_port', {guest: 22, host: 2222, id: 'ssh', auto_correct: true}]

suites:
  - name: default
    run_list:
      - recipe[hello::default]
    chef_client:
      config:
        log_level: ":debug"
        http_proxy: <%= ENV['http_proxy'] %>
        https_proxy: <%= ENV['https_proxy'] %>
        no_proxy: <%= ENV['no_proxy'] %>

verifier:
   name: inspec
   sudo: true
